Repository techno-link/zero-client, pull requests merged in 2024-04, with the labels that each got.

#22 fix(ansible): correct indentation for disabling screensaver command
  ansible/zero.yml
Labels: Review effort [1-5]: 1, bug_fix

#25 fix ansible script in zero.yml
  ansible/zero.yml
Labels: enhancement, Review effort [1-5]: 2

#26 Remove last updates from zero.yml
  ansible/zero.yml
Labels: enhancement, Review effort [1-5]: 1

#27 Disable lockscreen
  ansible/zero.yml
Labels: enhancement, Review effort [1-5]: 1
